id = 'Weyland Consortium: Building a Better World'
deck = '''
3 Hostile Takeover
3 Priority Requisition
1 Private Security Force
3 Project Atlas
2 Melange Mining Corp.
3 PAD Campaign
3 Project Junebug
2 Research Station
3 Beanstalk Royalties
3 Hedge Fund
2 Shipment from Kaguya
2 Hadrian's Wall
2 Ice Wall
2 Wall of Static
2 Wall of Thorns
3 Enigma
2 Tollbooth
2 Archer
2 Neural Katana
2 Rototurret
2 Shadow
'''