id = 'Kate "Mac" McCaffrey: Digital Tinker'
deck = '''
3 Diesel
2 Forged Activation Orders
3 Infiltration
2 Modded
2 Special Order
2 Stimhack
3 Sure Gamble
3 The Maker's Eye
3 Tinkering
2 Akamatsu Mem Chip
2 The Personal Touch
1 The Toolbox
1 Aesop's Pawnshop
3 Armitage Codebusting
2 Sacrificial Construct
1 Battering Ram
2 Corroder
2 Gordian Blade
1 Mimic
2 Pipeline
1 ZU.13 Key Master
2 Magnum Opus
'''